import re
import requests
import folium

print("--- SOC Threat Intelligence Platform Started ---\n")

#Download real server logs
log_url = "https://raw.githubusercontent.com/logpai/loghub/master/Linux/Linux_2k.log"
print("[+] Downloading Linux server log dataset...")
log_data = requests.get(log_url).text.splitlines()

log_pattern = r"authentication failure;.*rhost=(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})"
failed_logins = {}

print("[+] Parsing logs for brute-force attacks...")
for line in log_data:
    match = re.search(log_pattern, line)
    if match:
        ip = match.group(1)
        failed_logins[ip] = failed_logins.get(ip, 0) + 1

THRESHOLD = 10 
threat_data = []

print("\n--- 🚨 OSINT GEOLOCATION 🚨 ---")
for ip, count in failed_logins.items():
    if count >= THRESHOLD:
        try:
            # asking the API for the latitude and longitude
            geo = requests.get(f"http://ip-api.com/json/{ip}").json()
            if geo['status'] == 'success':
                print(f"[!] Threat: {ip:<15} | {geo['city']}, {geo['country']} | {count} attempts")
                
                # Save the exact coordinates for our map
                threat_data.append({
                    'ip': ip, 'count': count, 'lat': geo['lat'],
                    'lon': geo['lon'], 'city': geo['city'], 'isp': geo['isp']
                })
        except:
            print(f"[!] Threat tracking failed for {ip}")


# GENERATE INTERACTIVE THREAT MAP

print("\n[+] Generating Interactive Threat Map (threat_map.html)...")

# Initialize a dark-themed world map
threat_map = folium.Map(location=[20, 0], zoom_start=2, tiles="Cartodb dark_matter")

for threat in threat_data:
    # Add a glowing red dot for each hacker
    popup_text = f"IP: {threat['ip']}<br>Attacks: {threat['count']}<br>ISP: {threat['isp']}"
    
    folium.CircleMarker(
        location=[threat['lat'], threat['lon']],
        radius=8,
        color='red',
        fill=True,
        fill_color='red',
        fill_opacity=0.7,
        popup=folium.Popup(popup_text, max_width=200)
    ).add_to(threat_map)

# Save the map as a real webpage
threat_map.save("threat_map.html")



# AUTOMATED INCIDENT RESPONSE (SOAR)

print("[+] Generating Firewall Remediation Script (blocklist.sh)...")

with open("blocklist.sh", "w", encoding="utf-8") as f:
    f.write("#!/bin/bash\n")
    f.write("# Automated Firewall Blocklist generated by Threat Analyser\n\n")
    for threat in threat_data:
        f.write(f"iptables -A INPUT -s {threat['ip']} -j DROP  # {threat['city']}\n")

print("\n---  PLATFORM EXECUTION COMPLETE  ---")
print("1. Open 'threat_map.html' in your web browser to see the live attack map.")
print("2. Check 'blocklist.sh' for the automated firewall rules.")