#!/bin/bash
# Automated Firewall Blocklist generated by Threat Analyser

iptables -A INPUT -s 218.188.2.4 -j DROP  # Tsing Yi
iptables -A INPUT -s 65.166.159.14 -j DROP  # Cleveland
iptables -A INPUT -s 209.152.168.249 -j DROP  # Stockholm
iptables -A INPUT -s 60.30.224.116 -j DROP  # Wanghailou
iptables -A INPUT -s 195.129.24.210 -j DROP  # Roeselare
iptables -A INPUT -s 220.117.241.87 -j DROP  # Gwangjin-gu
iptables -A INPUT -s 150.183.249.110 -j DROP  # Yuseong
iptables -A INPUT -s 211.214.161.141 -j DROP  # Yongin-si
